import { ChildrenStatus, DrinkingHabit, EmotionalReadiness, Gender, LookingFor, MaritalStatus, PrismaClient, ProfileStatus, RelationshipTimeline, Role, SelfieStatus, SmokingHabit } from "@prisma/client";
import bcrypt from "bcrypt";

export async function seedUsers(prisma: PrismaClient) {
   console.log("Seeding dummy user profiles...");

   const passwordHash = await bcrypt.hash("asdfasdf", 10);

   const commonSelfieUrl = "1/selfie_front/70278098-2a48-45e9-8475-b65093279d35.jpg";

   const dummyProfiles = [
      {
         email: "aisha@gmail.com",
         name: "Aisha Rahman",
         age: 27,
         heightCm: 163,
         city: "Kochi",
         state: "Kerala",
         country: "India",
         lat: 9.9312,
         lng: 76.2673,
         religion: "Islam",
         motherTongue: "Malayalam",
         occupation: "Software Engineer",
         highestEducation: "B.Tech Computer Science",
         annualIncome: 1200000,
         maritalStatus: MaritalStatus.NEVER_MARRIED,
         bio: "I work as a software engineer and enjoy building meaningful products. I value honesty, deen, family, and a peaceful life.",
         languages: ["Malayalam", "English", "Hindi"],
         childrenStatus: ChildrenStatus.NO_CHILDREN,
         emotionalReadiness: EmotionalReadiness.YES,
         lookingFor: LookingFor.MARRIAGE,
         relationshipTimeline: RelationshipTimeline.ZERO_TO_SIX_MONTHS,
         smokingHabit: SmokingHabit.NO,
         drinkingHabit: DrinkingHabit.NO,
         imageUrl: "https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
         preference: {
            ageFrom: 27,
            ageTo: 33,
            heightFrom: 168,
            heightTo: 190,
            maritalStatus: [MaritalStatus.NEVER_MARRIED],
            religion: ["Islam"],
            motherTongue: ["Malayalam", "Urdu", "Hindi"],
            highestEducation: ["B.Tech", "M.Tech", "MBA", "MBBS"],
            occupation: ["Software Engineer", "Doctor", "Business", "Engineer"],
            annualIncomeFrom: 800000,
            annualIncomeTo: 3000000,
         },
      },
      {
         email: "sana@gmail.com",
         name: "Sana Malik",
         age: 25,
         heightCm: 158,
         city: "Bengaluru",
         state: "Karnataka",
         country: "India",
         lat: 12.9716,
         lng: 77.5946,
         religion: "Islam",
         motherTongue: "Urdu",
         occupation: "Doctor",
         highestEducation: "MBBS",
         annualIncome: 1500000,
         maritalStatus: MaritalStatus.NEVER_MARRIED,
         bio: "Doctor by profession, calm by nature. Looking for a kind, mature life partner who values both family and personal growth.",
         languages: ["Urdu", "English", "Hindi"],
         childrenStatus: ChildrenStatus.NO_CHILDREN,
         emotionalReadiness: EmotionalReadiness.YES,
         lookingFor: LookingFor.MARRIAGE,
         relationshipTimeline: RelationshipTimeline.ZERO_TO_SIX_MONTHS,
         smokingHabit: SmokingHabit.NO,
         drinkingHabit: DrinkingHabit.NO,
         imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Z2lybHxlbnwwfHwwfHx8MA%3D%3D",
         preference: {
            ageFrom: 27,
            ageTo: 35,
            heightFrom: 170,
            heightTo: 192,
            maritalStatus: [MaritalStatus.NEVER_MARRIED],
            religion: ["Islam"],
            motherTongue: ["Urdu", "Hindi", "English"],
            highestEducation: ["MBBS", "MD", "B.Tech", "MBA"],
            occupation: ["Doctor", "Software Engineer", "Business", "Civil Engineer"],
            annualIncomeFrom: 1000000,
            annualIncomeTo: 4000000,
         },
      },
      {
         email: "fatima@gmail.com",
         name: "Fatima Zahra",
         age: 29,
         heightCm: 165,
         city: "Hyderabad",
         state: "Telangana",
         country: "India",
         lat: 17.385,
         lng: 78.4867,
         religion: "Islam",
         motherTongue: "Urdu",
         occupation: "Teacher",
         highestEducation: "M.A English",
         annualIncome: 700000,
         maritalStatus: MaritalStatus.NEVER_MARRIED,
         bio: "I love teaching and spending time with family. Hoping to build a respectful, emotionally healthy marriage with shared values.",
         languages: ["Urdu", "English", "Telugu"],
         childrenStatus: ChildrenStatus.NO_CHILDREN,
         emotionalReadiness: EmotionalReadiness.YES,
         lookingFor: LookingFor.MARRIAGE,
         relationshipTimeline: RelationshipTimeline.ZERO_TO_SIX_MONTHS,
         smokingHabit: SmokingHabit.NO,
         drinkingHabit: DrinkingHabit.NO,
         imageUrl: "https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fGdpcmx8ZW58MHx8MHx8fDA%3D",
         preference: {
            ageFrom: 29,
            ageTo: 36,
            heightFrom: 168,
            heightTo: 190,
            maritalStatus: [MaritalStatus.NEVER_MARRIED],
            religion: ["Islam"],
            motherTongue: ["Urdu", "Malayalam", "Hindi"],
            highestEducation: ["M.A", "MBA", "B.Tech", "M.Tech"],
            occupation: ["Teacher", "Software Engineer", "Manager", "Business"],
            annualIncomeFrom: 700000,
            annualIncomeTo: 2500000,
         },
      },
      {
         email: "nadia@gmail.com",
         name: "Nadia Khan",
         age: 26,
         heightCm: 160,
         city: "Chennai",
         state: "Tamil Nadu",
         country: "India",
         lat: 13.0827,
         lng: 80.2707,
         religion: "Islam",
         motherTongue: "Tamil",
         occupation: "Graphic Designer",
         highestEducation: "B.Des",
         annualIncome: 850000,
         maritalStatus: MaritalStatus.NEVER_MARRIED,
         bio: "Creative, family-oriented, and simple. I enjoy design, travel, and meaningful conversations.",
         languages: ["Tamil", "English", "Hindi"],
         childrenStatus: ChildrenStatus.NO_CHILDREN,
         emotionalReadiness: EmotionalReadiness.YES,
         lookingFor: LookingFor.MARRIAGE,
         relationshipTimeline: RelationshipTimeline.ZERO_TO_SIX_MONTHS,
         smokingHabit: SmokingHabit.NO,
         drinkingHabit: DrinkingHabit.NO,
         imageUrl: "https://images.unsplash.com/photo-1604004215402-e0be233f39be?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fGdpcmx8ZW58MHx8MHx8fDA%3D",
         preference: {
            ageFrom: 27,
            ageTo: 34,
            heightFrom: 169,
            heightTo: 188,
            maritalStatus: [MaritalStatus.NEVER_MARRIED],
            religion: ["Islam"],
            motherTongue: ["Tamil", "Malayalam", "Hindi"],
            highestEducation: ["B.Des", "B.Tech", "MBA", "MCA"],
            occupation: ["Designer", "Software Engineer", "Architect", "Business"],
            annualIncomeFrom: 700000,
            annualIncomeTo: 2800000,
         },
      },
      {
         email: "mariam@gmail.com",
         name: "Mariam Siddiqui",
         age: 28,
         heightCm: 162,
         city: "Mumbai",
         state: "Maharashtra",
         country: "India",
         lat: 19.076,
         lng: 72.8777,
         religion: "Islam",
         motherTongue: "Hindi",
         occupation: "Accountant",
         highestEducation: "M.Com",
         annualIncome: 950000,
         maritalStatus: MaritalStatus.NEVER_MARRIED,
         bio: "Grounded, practical, and family-focused. I believe marriage works best with friendship, trust, and mutual effort.",
         languages: ["Hindi", "English", "Urdu"],
         childrenStatus: ChildrenStatus.NO_CHILDREN,
         emotionalReadiness: EmotionalReadiness.YES,
         lookingFor: LookingFor.MARRIAGE,
         relationshipTimeline: RelationshipTimeline.ZERO_TO_SIX_MONTHS,
         smokingHabit: SmokingHabit.NO,
         drinkingHabit: DrinkingHabit.NO,
         imageUrl: "https://plus.unsplash.com/premium_photo-1673792686134-f8cbeb0ad3e3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
         preference: {
            ageFrom: 28,
            ageTo: 35,
            heightFrom: 170,
            heightTo: 192,
            maritalStatus: [MaritalStatus.NEVER_MARRIED],
            religion: ["Islam"],
            motherTongue: ["Hindi", "Urdu", "Malayalam"],
            highestEducation: ["M.Com", "MBA", "CA", "B.Tech"],
            occupation: ["Accountant", "Finance", "Software Engineer", "Business"],
            annualIncomeFrom: 900000,
            annualIncomeTo: 3500000,
         },
      },
   ];

   for (const p of dummyProfiles) {
      const dob = new Date();
      dob.setFullYear(dob.getFullYear() - p.age);

      // 1) Create or update user
      const user = await prisma.user.upsert({
         where: { email: p.email },
         update: {
            password: passwordHash,
            isVerified: true,
            role: Role.USER,
            isBlocked: false,
            isDeleted: false,
         },
         create: {
            email: p.email,
            password: passwordHash,
            isVerified: true,
            role: Role.USER,
         },
      });

      // 2) Create or update profile
      const profile = await prisma.profile.upsert({
         where: { userId: user.id },
         update: {
            name: p.name,
            gender: Gender.FEMALE,
            dateOfBirth: dob,
            maritalStatus: p.maritalStatus,
            heightCm: p.heightCm,
            religion: p.religion,
            motherTongue: p.motherTongue,
            city: p.city,
            state: p.state,
            country: p.country,
            lastLocationLat: p.lat,
            lastLocationLng: p.lng,
            highestEducation: p.highestEducation,
            occupation: p.occupation,
            annualIncome: p.annualIncome,
            bio: p.bio,
            languages: p.languages,
            childrenStatus: p.childrenStatus,
            emotionalReadiness: p.emotionalReadiness,
            lookingFor: p.lookingFor,
            relationshipTimeline: p.relationshipTimeline,
            smokingHabit: p.smokingHabit,
            drinkingHabit: p.drinkingHabit,
            profileCompletion: 100,
            profileStatus: ProfileStatus.COMPLETED,
            hasCompletedBasicDetails: true,
            hasCompletedPartnerPreference: true,
            hasCompletedImageUpload: true,
            selfieUrl: commonSelfieUrl,
            leftSelfieUrl: commonSelfieUrl,
            rightSelfieUrl: commonSelfieUrl,
            selfieStatus: SelfieStatus.APPROVED,
         },
         create: {
            userId: user.id,
            name: p.name,
            gender: Gender.FEMALE,
            dateOfBirth: dob,
            maritalStatus: p.maritalStatus,
            heightCm: p.heightCm,
            religion: p.religion,
            motherTongue: p.motherTongue,
            city: p.city,
            state: p.state,
            country: p.country,
            lastLocationLat: p.lat,
            lastLocationLng: p.lng,
            highestEducation: p.highestEducation,
            occupation: p.occupation,
            annualIncome: p.annualIncome,
            bio: p.bio,
            languages: p.languages,
            childrenStatus: p.childrenStatus,
            emotionalReadiness: p.emotionalReadiness,
            lookingFor: p.lookingFor,
            relationshipTimeline: p.relationshipTimeline,
            smokingHabit: p.smokingHabit,
            drinkingHabit: p.drinkingHabit,
            profileCompletion: 100,
            profileStatus: ProfileStatus.COMPLETED,
            hasCompletedBasicDetails: true,
            hasCompletedPartnerPreference: true,
            hasCompletedImageUpload: true,
            selfieUrl: commonSelfieUrl,
            leftSelfieUrl: commonSelfieUrl,
            rightSelfieUrl: commonSelfieUrl,
            selfieStatus: SelfieStatus.APPROVED,
         },
      });

      // 3) Replace old profile images
      await prisma.userImage.deleteMany({
         where: { profileId: profile.id },
      });

      await prisma.userImage.create({
         data: {
            profileId: profile.id,
            imageUrl: p.imageUrl,
            isPrimary: true,
         },
      });

      // 4) Create or update partner preference
      await prisma.partnerPreference.upsert({
         where: { userId: user.id },
         update: {
            ageFrom: p.preference.ageFrom,
            ageTo: p.preference.ageTo,
            heightFrom: p.preference.heightFrom,
            heightTo: p.preference.heightTo,
            maritalStatus: p.preference.maritalStatus,
            religion: p.preference.religion,
            motherTongue: p.preference.motherTongue,
            highestEducation: p.preference.highestEducation,
            occupation: p.preference.occupation,
            annualIncomeFrom: p.preference.annualIncomeFrom,
            annualIncomeTo: p.preference.annualIncomeTo,
         },
         create: {
            userId: user.id,
            ageFrom: p.preference.ageFrom,
            ageTo: p.preference.ageTo,
            heightFrom: p.preference.heightFrom,
            heightTo: p.preference.heightTo,
            maritalStatus: p.preference.maritalStatus,
            religion: p.preference.religion,
            motherTongue: p.preference.motherTongue,
            highestEducation: p.preference.highestEducation,
            occupation: p.preference.occupation,
            annualIncomeFrom: p.preference.annualIncomeFrom,
            annualIncomeTo: p.preference.annualIncomeTo,
         },
      });

      console.log(`User seeded: ${p.name}`);
   }

   console.log("Dummy user profiles seeded successfully!");
}
