export enum NotificationType {
   NEW_MESSAGE = "NEW_MESSAGE",
   NEW_LIKE = "NEW_LIKE",
   NEW_MATCH = "NEW_MATCH",
   INTEREST_ACCEPTED = "INTEREST_ACCEPTED",
   MISSED_CALL = "MISSED_CALL",
   IMAGE_ACCESS_REQUESTED = "IMAGE_ACCESS_REQUESTED",
   IMAGE_ACCESS_GRANTED = "IMAGE_ACCESS_GRANTED",
   PROFILE_APPROVED = "PROFILE_APPROVED",
   PROFILE_REJECTED = "PROFILE_REJECTED",
   SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS",
   SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
   PAYMENT_FAILED = "PAYMENT_FAILED",
}

